baseURL = "https://sholokhov.pro"
title = "Artem Sholokhov"
locale = "en-us"
relativeURLs = true
enableEmoji = true
enableRobotsTXT = true
copyright = "&copy; 2026, Artem Sholokhov"
[taxonomies]
  tag = "tags"

[markup]
  [markup.highlight]
    style = "github"
    lineNos = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 20
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 50
  [[menu.main]]
    identifier = "talks"
    name = "Talks"
    url = "/talks/"
    weight = 65
  [[menu.main]]
    identifier = "photos"
    name = "Photos"
    url = "/photos/"
    weight = 70
  [[menu.main]]
    identifier = "hire-me"
    name = "Hire Me"
    url = "/hire-me/"
    weight = 100
    [menu.main.params]
      separator = true

[params]
  description = "Artem Sholokhov - Software Engineer and Architect, Amsterdam"
  header_title = "Artem Sholokhov"
  header_subtitle = "Software Engineer and Architect | 🇳🇱 Amsterdam"
  home_image = "/images/me.jpeg"
  mainSections = ["blog"]
  caseStudyTag = "case-study"
  instagram = "https://www.instagram.com/sholokhov_a/"
  [[params.social]]
    icon = "github"
    href = "https://github.com/sholokhov"
    label = "GitHub"
  [[params.social]]
    icon = "linkedin"
    href = "https://www.linkedin.com/in/artem-sholokhov-5880206a/"
    label = "LinkedIn"
  [[params.social]]
    icon = "telegram"
    href = "https://t.me/sholokhov"
    label = "Telegram"
  [[params.social]]
    icon = "instagram"
    href = "https://www.instagram.com/sholokhov_a/"
    label = "Instagram"
  [[params.social]]
    icon = "email"
    href = "mailto:sholokhov.pro.k8bx9@passmail.net"
    label = "Email"
